backend/foodcartapp/urls.py
from django.urls import path

from .views import banners_list_api, product_list_api, register_order

app_name = "foodcartapp"

urlpatterns = [
    path("products/", product_list_api),
    path("banners/", banners_list_api),
    path("order/", register_order),
]

backend/restaurateur/urls.py
from django.shortcuts import redirect
from django.urls import path

from . import views

app_name = "restaurateur"

urlpatterns = [
    path("", lambda request: redirect("restaurateur:ProductsView")),
    path("products/", views.view_products, name="ProductsView"),
    path("restaurants/", views.view_restaurants, name="RestaurantView"),
    # TODO заглушка для нереализованного функционала
    path("orders/", views.view_orders, name="view_orders"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
]

backend/star_burger/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import render
from django.urls import include, path

from . import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api-auth/", include("rest_framework.urls")),
    path("", render, kwargs={"template_name": "index.html"}, name="start_page"),
    path("api/", include("foodcartapp.urls")),
    path("manager/", include("restaurateur.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path(r"__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

backend/foodcartapp/models.py
from django.core.validators import (
    MaxValueValidator,
    MinLengthValidator,
    MinValueValidator,
)
from django.db import models
from django.db.models import Sum
from django.utils import timezone
from geopy import distance
from phonenumber_field.modelfields import PhoneNumberField

from locations.models import Location


class Restaurant(models.Model):
    name = models.CharField("название", max_length=50)
    address = models.CharField(
        "адрес",
        max_length=100,
        blank=True,
    )
    location = models.ForeignKey(
        to=Location,
        verbose_name="локация",
        on_delete=models.SET_NULL,
        related_name="restaurants",
        null=True,
        blank=True,
    )
    contact_phone = models.CharField(
        "контактный телефон",
        max_length=50,
        blank=True,
    )

    class Meta:
        verbose_name = "ресторан"
        verbose_name_plural = "рестораны"

    def __str__(self):
        return self.name


class ProductQuerySet(models.QuerySet):
    def available(self):
        products = RestaurantMenuItem.objects.filter(availability=True).values_list(
            "product"
        )
        return self.filter(pk__in=products)


class ProductCategory(models.Model):
    name = models.CharField("название", max_length=50)

    class Meta:
        verbose_name = "категория"
        verbose_name_plural = "категории"

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField("название", max_length=50)
    category = models.ForeignKey(
        ProductCategory,
        verbose_name="категория",
        related_name="products",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
    )
    price = models.DecimalField(
        "цена", max_digits=8, decimal_places=2, validators=[MinValueValidator(0)]
    )
    image = models.ImageField("картинка")
    special_status = models.BooleanField(
        "спец.предложение",
        default=False,
        db_index=True,
    )
    description = models.TextField(
        "описание",
        max_length=200,
        blank=True,
    )

    objects = ProductQuerySet.as_manager()

    class Meta:
        verbose_name = "товар"
        verbose_name_plural = "товары"

    def __str__(self):
        return self.name


class RestaurantMenuItem(models.Model):
    restaurant = models.ForeignKey(
        Restaurant,
        related_name="menu_items",
        verbose_name="ресторан",
        on_delete=models.CASCADE,
    )
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        related_name="menu_items",
        verbose_name="продукт",
    )
    availability = models.BooleanField("в продаже", default=True, db_index=True)

    class Meta:
        verbose_name = "пункт меню ресторана"
        verbose_name_plural = "пункты меню ресторана"
        unique_together = [["restaurant", "product"]]

    def __str__(self):
        return f"{self.restaurant.name} - {self.product.name}"


class OrderQuerySet(models.QuerySet):
    def with_total_prices(self):
        return self.annotate(total_price=Sum("order_products__static_price"))

    def with_restaurants(self):
        orders = self.select_related("restaurant", "location").prefetch_related(
            "order_products__product"
        )
        restaurant_menu_items = (
            RestaurantMenuItem.objects.prefetch_related("restaurant__location")
            .select_related("product")
            .filter(availability=True)
        )

        # Build {Restaurant: set(Products)} dict
        restaurants_and_products = {
            entry.restaurant: set() for entry in restaurant_menu_items
        }
        for entry in restaurant_menu_items:
            restaurants_and_products[entry.restaurant].add(entry.product)

        for order in orders:
            order_products = set(entry.product for entry in order.order_products.all())

            order.suitable_restaurants = []
            for restaurant, products in restaurants_and_products.items():
                if order_products.issubset(products):
                    order.suitable_restaurants.append(restaurant)

        return orders

    def with_distances(self):
        # Use only after `with_restaurants()` QuerySet method:
        # orders must have `suitable_restaurants`.

        for order in self:
            order_coordinates = order.location.latitude, order.location.longitude
            suitable_restaurants_with_distances = []

            for restaurant in order.suitable_restaurants:
                restaurant_coordinates = (
                    restaurant.location.latitude,
                    restaurant.location.longitude,
                )
                restaurant_distance = distance.distance(
                    order_coordinates, restaurant_coordinates
                ).km

                suitable_restaurants_with_distances.append(
                    (restaurant, restaurant_distance)
                )

            order.suitable_restaurants_with_distances = (
                suitable_restaurants_with_distances
            )

        return self


class Order(models.Model):
    # Order status choices
    NEW = 0
    CONFIRMED = 1
    COOKING = 2
    DELIVERY = 3
    FINISHED = 4
    STATUS_CHOICES = [
        (NEW, "Новый"),
        (CONFIRMED, "Подтвержден"),
        (COOKING, "Готовка"),
        (DELIVERY, "Доставка"),
        (FINISHED, "Выполнен"),
    ]

    # Payment choices
    CREDIT_CARD = 0
    CASH = 1
    PAYMENT_CHOICES = [
        (CREDIT_CARD, "карта"),
        (CASH, "наличные"),
    ]

    first_name = models.CharField(
        verbose_name="имя",
        max_length=20,
    )
    last_name = models.CharField(
        verbose_name="фамилия",
        max_length=40,
    )
    phone_number = PhoneNumberField(
        verbose_name="номер телефона",
        db_index=True,
    )
    address = models.CharField(
        verbose_name="адрес доставки",
        max_length=100,
        validators=[MinLengthValidator(10)],
    )
    location = models.ForeignKey(
        to=Location,
        verbose_name="локация",
        on_delete=models.SET_NULL,
        related_name="orders",
        null=True,
        blank=True,
    )
    comment = models.TextField(
        verbose_name="комментарий",
        max_length=500,
        blank=True,
    )
    status = models.PositiveSmallIntegerField(
        choices=STATUS_CHOICES,
        default=NEW,
        db_index=True,
    )
    payment = models.PositiveSmallIntegerField(
        choices=PAYMENT_CHOICES,
        default=CREDIT_CARD,
        db_index=True,
    )
    restaurant = models.ForeignKey(
        Restaurant,
        on_delete=models.CASCADE,
        verbose_name="готовит",
        related_name="orders",
        null=True,
        blank=True,
    )
    registered_at = models.DateTimeField(
        verbose_name="оформлен",
        default=timezone.now,
        db_index=True,
    )
    called_at = models.DateTimeField(
        verbose_name="подтвержден",
        db_index=True,
        blank=True,
        null=True,
    )
    delivered_at = models.DateTimeField(
        verbose_name="доставлен",
        db_index=True,
        blank=True,
        null=True,
    )

    objects = OrderQuerySet.as_manager()

    class Meta:
        verbose_name = "заказ"
        verbose_name_plural = "заказы"

    def __str__(self):
        return f"{self.first_name}, {self.address}"


class OrderProduct(models.Model):
    order = models.ForeignKey(
        to=Order,
        verbose_name="состав заказа",
        related_name="order_products",
        on_delete=models.CASCADE,
    )
    product = models.ForeignKey(
        to=Product,
        verbose_name="продукт",
        related_name="order_products",
        on_delete=models.CASCADE,
    )
    amount = models.PositiveSmallIntegerField(
        verbose_name="количество",
        validators=[MinValueValidator(1), MaxValueValidator(10)],
    )
    static_price = models.DecimalField(
        verbose_name="Фиксированная стоимость",
        max_digits=8,
        decimal_places=2,
        validators=[MinValueValidator(0)],
    )

    class Meta:
        verbose_name = "позиция заказа"
        verbose_name_plural = "позиции заказа"

    def __str__(self):
        return f"{self.product} - {self.amount}"

backend/restaurateur/models.py
from django.db import models

# Create your models here.

backend/restaurateur/views.py
from django import forms
from django.contrib.auth import authenticate, login
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import View

from foodcartapp.models import Order, Product, Restaurant
from locations.geocoding import fetch_coordinates
from locations.models import Location


class Login(forms.Form):
    username = forms.CharField(
        label="Логин",
        max_length=75,
        required=True,
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Укажите имя пользователя"}
        ),
    )
    password = forms.CharField(
        label="Пароль",
        max_length=75,
        required=True,
        widget=forms.PasswordInput(
            attrs={"class": "form-control", "placeholder": "Введите пароль"}
        ),
    )


class LoginView(View):
    def get(self, request, *args, **kwargs):
        form = Login()
        return render(request, "login.html", context={"form": form})

    def post(self, request):
        form = Login(request.POST)

        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]

            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                if user.is_staff:  # FIXME replace with specific permission
                    return redirect("restaurateur:RestaurantView")
                return redirect("start_page")

        return render(
            request,
            "login.html",
            context={
                "form": form,
                "ivalid": True,
            },
        )


class LogoutView(auth_views.LogoutView):
    next_page = reverse_lazy("restaurateur:login")


def is_manager(user):
    return user.is_staff  # FIXME replace with specific permission


@user_passes_test(is_manager, login_url="restaurateur:login")
def view_products(request):
    restaurants = list(Restaurant.objects.order_by("name"))
    products = list(Product.objects.prefetch_related("menu_items", "category"))

    default_availability = {restaurant.id: False for restaurant in restaurants}
    products_with_restaurants = []
    for product in products:

        availability = {
            **default_availability,
            **{
                item.restaurant_id: item.availability
                for item in product.menu_items.all()
            },
        }
        orderer_availability = [
            availability[restaurant.id] for restaurant in restaurants
        ]

        products_with_restaurants.append((product, orderer_availability))

    return render(
        request,
        template_name="products_list.html",
        context={
            "products_with_restaurants": products_with_restaurants,
            "restaurants": restaurants,
        },
    )


@user_passes_test(is_manager, login_url="restaurateur:login")
def view_restaurants(request):
    restaurants = Restaurant.objects.all()
    restaurants_addresses = restaurants.values_list("address", flat=True)
    restaurants_addresses_with_locations = Location.objects.filter(
        address__in=restaurants_addresses
    ).values_list("address", flat=True)

    for address in restaurants_addresses:
        if address not in restaurants_addresses_with_locations:
            latitude, longitude = fetch_coordinates(address)
            Location.objects.create(
                address=address,
                longitude=longitude,
                latitude=latitude,
            )
        else:
            continue

    return render(
        request,
        template_name="restaurants_list.html",
        context={
            "restaurants": restaurants,
        },
    )


@user_passes_test(is_manager, login_url="restaurateur:login")
def view_orders(request):
    orders = (
        Order.objects.order_by("status")
        .with_total_prices()
        .with_restaurants()
        .with_distances()
    )

    return render(
        request,
        template_name="order_items.html",
        context={"orders": orders},
    )

backend/restaurateur/templates/base_restaurateur_page.html
<!doctype html>{% load static %}
<html lang="ru">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="icon" href="{% static 'icon.png' %}" type="image/x-icon">

  <title>{% block title %}{% endblock %}</title>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
</head>
<body>

  {% block header_nav %}
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="{% url 'restaurateur:ProductsView' %}">Star Burger</a>
        </div>
        <ul class="nav navbar-nav">
          <li>
            <a href="{% url 'restaurateur:ProductsView' %}">Меню</a>
          </li>
          <li>
            <a href="{% url 'restaurateur:RestaurantView' %}">Рестораны</a>
          </li>
          <li>
            <a href="{% url 'restaurateur:view_orders' %}">Заказы</a>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <a href="{% url 'restaurateur:logout' %}"><span class="glyphicon glyphicon-log-out"></span> Выйти</a>
          </li>
        </ul>
      </div>
    </nav>
  {% endblock header_nav %}

  {% block content %}{% endblock %}

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
</body>
</html>

backend/restaurateur/templates/login.html
{% extends 'base_restaurateur_page.html' %}

{% block header_nav %}{% endblock %}

{% block title %}Авторизация | Star Burger{% endblock %}


{% block content %}
  <br/>
  <br/>
  <br/>

  <center>
    <h2>Авторизация</h2>

    <hr/>

    <div class="row">
      <div class="col-sm-4 col-md-4 col-lg-4"></div>
      <div class="col-sm-4 col-md-4 col-lg-4">
        <form method="post">
          {% csrf_token %}

          {{ form.non_field_errors }}

          {% if ivalid %}
            <div class="alert alert-danger" role="alert">Неверный логин / пароль.</div>
          {% endif %}

          <input type="hidden" name="next" value="{{ request.GET.next }}"/>

          {{form.as_p}}
          <button class="btn btn-primary" type="submit">Войти</button>
        </form>
      </div>
      <div class="col-sm-4 col-md-4 col-lg-4"></div>

    </div>
  </center>
{% endblock %}

backend/restaurateur/templates/order_items.html
{% extends 'base_restaurateur_page.html' %}

{% block title %}Необработанные заказы | Star Burger{% endblock %}

{% block content %}
<center>
  <h2>Необработанные заказы</h2>
</center>

<hr />
<br />
<br />
<div class="container">
  <table class="table table-responsive">
    <tr>
      <th>ID заказа</th>
      <th>Статус заказа</th>
      <th>Способ оплаты</th>
      <th>Стоимость заказа</th>
      <th>Клиент</th>
      <th>Телефон</th>
      <th>Адрес доставки</th>
      <th>Комментарий</th>
      <th>Ресторан</th>
      <th>Ссылка на редактирование</th>
    </tr>

    {% for order in orders %}
    <tr>
      <td>{{ order.id }}</td>
      <td>{{ order.get_status_display }}</td>
      <td>{{ order.get_payment_display }}</td>
      <td>{{ order.total_price }}</td>
      <td>{{ order.first_name }} {{ order.last_name }}</td>
      <td>{{ order.phone_number }}</td>
      <td>{{ order.address }}</td>
      <td>{{ order.comment }}</td>
      <td>

        {% if order.restaurant %}
        <li>{{ order.restaurant }}</li>

        {% elif order.suitable_restaurants_with_distances %}
        <details>
          <summary>Рестораны</summary>
          {% for restaurant, distance in order.suitable_restaurants_with_distances %}
          <li>
            {{ restaurant.name }} - {{ distance|floatformat:2 }} км.
          </li>
          {% endfor %}
        </details>

        {% else %}
        <li>No suitable restaurants!</li>
        {% endif %}
      </td>
      <td><a
          href="{% url 'admin:foodcartapp_order_change' object_id=order.id %}?next={{ request.get_full_path|urlencode }}">Редактировать</a>
      </td>
      </td>

    </tr>
    {% endfor %}
  </table>
</div>
{% endblock %}

backend/restaurateur/templates/products_list.html
{% extends 'base_restaurateur_page.html' %}

{% block title %}Меню | Star Burger{% endblock %}

{% block content %}

  <center>
    <h2>Ваше меню</h2>
  </center>

  <hr/>

  <br/>
  <br/>

  <div class="container">
   <table class="table table-responsive">
      <tr>
        <th></th>
        <th>Название</th>
        <th>Категория</th>
        <th>Цена</th>
        {% for restaurant in restaurants %}
          <th>{{ restaurant.name }}</th>
        {% endfor %}
        <th>Действия</th>
      </tr>

      {% for product, availability in products_with_restaurants %}
        <tr>
          <td><img src="{{product.image.url}}" alt="{{product.name}}" height="50px"></td>
          <td>{{product.name}}</td>
          <td>{{product.category}}</td>
          <td>{{product.price}}</td>

          {% for available in availability %}
            <td>
              {% if available %}
                <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 367.805 367.805" style="enable-background:new 0 0 367.805 367.805;" xml:space="preserve" width="20" height="20">
                  <g>
                    <path style="fill:#3BB54A;" d="M183.903,0.001c101.566,0,183.902,82.336,183.902,183.902s-82.336,183.902-183.902,183.902
                    S0.001,285.469,0.001,183.903l0,0C-0.288,82.625,81.579,0.29,182.856,0.001C183.205,0,183.554,0,183.903,0.001z"/>
                    <polygon style="fill:#D4E1F4;" points="285.78,133.225 155.168,263.837 82.025,191.217 111.805,161.96 155.168,204.801
                    256.001,103.968   "/>
                  </g>
                </svg>
              {% else %}
                <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 512 512" style="enable-background:new 0 0 512 512;" xml:space="preserve" width="20" height="20">
                  <ellipse style="fill:#E21B1B;" cx="256" cy="256" rx="256" ry="255.832"/>
                    <g>
                      <rect x="228.021" y="113.143" transform="matrix(0.7071 -0.7071 0.7071 0.7071 -106.0178 256.0051)" style="fill:#FFFFFF;" width="55.991" height="285.669"/>

                      <rect x="113.164" y="227.968" transform="matrix(0.7071 -0.7071 0.7071 0.7071 -106.0134 255.9885)" style="fill:#FFFFFF;" width="285.669" height="55.991"/>
                    </g>
                </svg>
              {% endif %}
            </td>
          {% endfor %}
          <td>
            <a href="{% url 'admin:foodcartapp_product_change' product.id %}">ред.</a>
          </td>
        </tr>
      {% endfor %}
    </table>

    <a href="{% url 'admin:foodcartapp_product_add' %}" class="btn btn-default">Добавить</a>

  </div>
{% endblock %}

backend/restaurateur/templates/restaurants_list.html
{% extends 'base_restaurateur_page.html' %}

{% block title %}Рестораны | Star Burger{% endblock %}

{% block content %}

  <div class="container">
    <center>
      <h2>Ваши рестораны</h2>
    </center>

    <hr/>

    <table class="table table-responsive">
      <tr>
        <th>Название</th>
        <th>Адрес</th>
        <th>Контактный телефон</th>
        <th>Действия</th>
      </tr>

      {% for restaurant in restaurants %}
        <tr>
          <td>{{ restaurant.name }}</td>
          <td>
            {{ restaurant.address|default:'пусто' }}</td>
          <td>
            {% if restaurant.contact_phone %}
              <a href="phone:{{ restaurant.contact_phone }}">{{ restaurant.contact_phone }}</a>
            {% else %}
              пусто
            {% endif %}
          </td>
          <td>
            <a href="{% url 'admin:foodcartapp_restaurant_change' restaurant.id %}">ред.</a>
          </td>
        </tr>
      {% endfor %}
    </table>

    <a href="{% url 'admin:foodcartapp_restaurant_add' %}" class="btn btn-default">Добавить</a>

  </div>
{% endblock %}